apiVersion: v1
kind: Service
metadata:
  name: code-talk-client
  namespace: code-talk
  labels:
    app: code-talk
    component: client
spec:
  type: ClusterIP
  selector:
    app: code-talk
    component: client
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  sessionAffinity: None
