apiVersion: v1
kind: Service
metadata:
  name: code-talk-client
  namespace: default
  labels:
    app: code-talk
    component: client
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: code-talk
    component: client
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
