apiVersion: v1
kind: Service
metadata:
  name: code-talk-server
  namespace: code-talk
  labels:
    app: code-talk
    component: server
spec:
  type: ClusterIP
  selector:
    app: code-talk
    component: server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
